blog_post_management_system/accounts/interface/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import (
    ProfileDetailView,
    ProfileUpdateView,
    RegistrationView,
    CustomLoginView,
)

urlpatterns = [
    # path("",views.home_page,name = ""),
    path("registration/", RegistrationView.as_view(), name="user-registration"),
    path("login/", CustomLoginView.as_view(), name="user-login"),
    path("logout/", views.logout_view, name="user-logout"),
    path("blogs/", include("blogs.interface.urls"), name="blogs"),
    path("userprofile/", ProfileDetailView.as_view(), name="profile"),
    path("userprofile/edit", ProfileUpdateView.as_view(), name="profile_edit"),
]

blog_post_management_system/blog_post_management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import home_page

urlpatterns = [
    path("",views.home_page,name = 'home_page'),
    path('admin/', admin.site.urls, name = "admin_view"),
    path("accounts/",include("accounts.interface.urls")),
    path("blogs/",include("blogs.interface.urls")),
    path("comments/",include("comments.interface.urls")),
    path("likes/",include("likes.interface.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_post_management_system/comments/urls.py
from django.urls import path, include
from .views import CommentListView,CommentCreateView,CommentDeleteView

urlpatterns = [
    path("<int:pk>/", CommentListView.as_view(), name="list_comment"),
    path('<int:pk>/new/',CommentCreateView.as_view(), name='create_comment'),
    path('<int:pk>/delete/',CommentDeleteView.as_view(), name='delete_comment'),
]

blog_post_management_system/accounts/domain/models.py
from django.db import models
from django.contrib.auth.models import User  


class UserProfile(models.Model):
    """This model is joined with built in User model"""

    user = models.OneToOneField(User, on_delete=models.CASCADE)  
    bio = models.TextField(blank=True)  
    profile_picture = models.ImageField(upload_to='profiles/profile_pictures/', blank=True, null=True)  

    def __str__(self):
        return f"{self.user.username}'s Profile"

blog_post_management_system/accounts/application/forms.py
from django import forms
from django.core.validators import EmailValidator, MinLengthValidator
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms.widgets import PasswordInput, TextInput
from ..domain.models import UserProfile
from django.core.exceptions import ValidationError
from django.core.validators import EmailValidator


# - Create/Register a user (Model Form)
class CreateUserForm(UserCreationForm):
    email = forms.EmailField(
        validators=[EmailValidator(message="Invalid email address.")]
    )
    first_name = forms.CharField(max_length=20, required=True)
    last_name = forms.CharField(max_length=20, required=True)

    class meta:
        model = User
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
        ]

    def save(self, commit=True):
        user = super(CreateUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user


# Authenticate a user (Model form)
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(), required=True)
    password = forms.CharField(widget=PasswordInput(), required=True)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ["bio", "profile_picture"]

blog_post_management_system/accounts/forms.py
from django import forms
from django.core.validators import EmailValidator, MinLengthValidator
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms.widgets import PasswordInput, TextInput
from .models import UserProfile
from django.core.exceptions import ValidationError
from django.core.validators import EmailValidator


# - Create/Register a user (Model Form)
class CreateUserForm(UserCreationForm):
    email = forms.EmailField(
        validators=[EmailValidator(message="Invalid email address.")]
    )
    first_name = forms.CharField(max_length=20, required=True)
    last_name = forms.CharField(max_length=20, required=True)

    class meta:
        model = User
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
        ]

    def save(self, commit=True):
        user = super(CreateUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user


# Authenticate a user (Model form)
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(), required=True)
    password = forms.CharField(widget=PasswordInput(), required=True)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ["bio", "profile_picture"]

blog_post_management_system/accounts/interface/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import auth
from django.contrib.auth import authenticate, login, logout
from accounts.application.forms import CreateUserForm, LoginForm
from django.contrib.auth.decorators import login_required
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView
from accounts.domain.models import UserProfile
from accounts.application.forms import UserProfileForm
from django.contrib import messages
from django.views.generic.edit import FormView
from django.contrib.auth.views import LoginView
from accounts.application.service import ProfileAppService


class RegistrationView(FormView):
    """This view is used for registering new user"""

    template_name = "accounts/registration.html"
    form_class = CreateUserForm
    success_url = reverse_lazy("user-login")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class CustomLoginView(LoginView):
    """This view is used for login Existing user"""

    template_name = "accounts/login.html"
    authentication_form = LoginForm
    redirect_authenticated_user = True
    success_url = reverse_lazy("blog_list")


def logout_view(request):
    """This view is used for logging out user"""

    logout(request)
    return redirect("home_page")


@login_required(login_url="user-login")
def user_profile(request):
    """This view is used for redirecting user to profile page"""

    return render(request, "accounts/profile.html")


class ProfileDetailView(LoginRequiredMixin, DetailView):
    """This view is used for listing profile details"""

    model = UserProfile
    template_name = "accounts/profile.html"
    context_object_name = "profile"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.service = ProfileAppService()

    def get_object(self):
        return self.service.get_profile_application(self.request.user)


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    """This view is used for profile update"""

    model = UserProfile
    form_class = UserProfileForm
    template_name = "accounts/edit_profile.html"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.service = ProfileAppService()

    def get_success_url(self):
        return reverse_lazy("profile")

    def get_object(self):
        return self.service.get_profile_application(self.request.user)

blog_post_management_system/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import auth
from django.contrib.auth import authenticate, login, logout
from .forms import CreateUserForm, LoginForm
from django.contrib.auth.decorators import login_required
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView
from .models import UserProfile
from .forms import UserProfileForm
from django.contrib import messages
from django.views.generic.edit import FormView
from django.contrib.auth.views import LoginView


class RegistrationView(FormView):
    """This view is used for registering new user"""

    template_name = "accounts/registration.html"
    form_class = CreateUserForm
    success_url = reverse_lazy("user-login")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class CustomLoginView(LoginView):
    """This view is used for login Existing user"""

    template_name = "accounts/login.html"
    authentication_form = LoginForm
    redirect_authenticated_user = True
    success_url = reverse_lazy("blog_list")


def logout_view(request):
    """This view is used for logging out user"""

    logout(request)
    return redirect("home_page")


@login_required(login_url="user-login")
def user_profile(request):
    """This view is used for redirecting user to profile page"""

    return render(request, "accounts/profile.html")


class ProfileDetailView(LoginRequiredMixin, DetailView):
    """This view is used for listing profile details"""

    model = UserProfile
    template_name = "accounts/profile.html"
    context_object_name = "profile"

    def get_object(self):
        profile, created = UserProfile.objects.get_or_create(user=self.request.user)
        return profile


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    """This view is used for profile update"""

    model = UserProfile
    form_class = UserProfileForm
    template_name = "accounts/edit_profile.html"

    def get_success_url(self):
        return reverse_lazy("profile")

    def get_object(self):
        profile, created = UserProfile.objects.get_or_create(user=self.request.user)
        return profile

blog_post_management_system/accounts/templates/accounts/edit_profile.html
{% extends "base_layout.html" %}
{% block title %}
    Profile Page
{% endblock title %}
{% block navigation-bar %}
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">Back to Profile</a>
        </li>
    </ul>
{% endblock navigation-bar %}
{% block page_body %}
    <div class="container mt-5">
        <h1 class="text-center mb-4">Edit Profile</h1>
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-header">
                        <h4>Update Your Profile Information</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="id_bio" class="form-label">Bio</label>
                                <textarea class="form-control" id="id_bio" name="bio" rows="3" >{{ form.bio.value|default_if_none:"" }}</textarea>
                            </div>
                            <div class="mb-3">
                                <label for="id_profile_picture" class="form-label">Profile Picture</label>
                                <input class="form-control"
                                       type="file"
                                       id="id_profile_picture"
                                       name="profile_picture">
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Save Changes</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock page_body %}

blog_post_management_system/accounts/templates/accounts/index.html
{% extends "base_layout.html" %}
{% block title %}Index Page{% endblock title %}
{% block page_body %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 text-center">
            <h1>Welcome to Our Platform</h1>
            <p class="lead">Please sign in or Register to continue.</p>
        </div>
    </div>
</div>
{% endblock page_body %}

blog_post_management_system/accounts/templates/accounts/login.html
{% extends "base_layout.html" %}
{% load static %}
{% block title %}
    Login Page
{% endblock title %}
{% block navigation-bar %}
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'user-registration' %}">Register</a>
        </li>
    </ul>
{% endblock navigation-bar %}
{% block page_body %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4">
                <div class="card shadow-sm">
                    <div class="card-header text-center">
                        <h4>Login</h4>
                    </div>
                    {% if form.non_field_errors %}
                        <div class="text-danger">
                            <ul>
                                {% for error in form.non_field_errors %}<li>{{ error }}</li>{% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="id_username" class="form-label">Username</label>
                                <input type="text"
                                       name="username"
                                       id="id_username"
                                       class="form-control"
                                       value="{{ form.username.value|default:'' }}">
                                {% if form.username.errors %}
                                    <ul>
                                        {% for error in form.username.errors %}<li class="text-danger">{{ error }}</li>{% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                            <div class="mb-3">
                                <label for="id_password" class="form-label">Password</label>
                                <input type="password"
                                       name="password"
                                       id="id_password"
                                       class="form-control"
                                       value="{{ form.password.value|default:'' }}">
                                {% if form.password.errors %}
                                    <ul class="text-danger">
                                        {% for error in form.password.errors %}<li>{{ error }}</li>{% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary w-100">Login</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock page_body %}

blog_post_management_system/accounts/templates/accounts/profile.html
{% extends "base_layout.html" %}
{% block title %}
    Profile Page
{% endblock title %}
{% block navigation-bar %}
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'profile_edit' %}">Edit Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'blog_list' %}">Back to Blogs</a>
        </li>
    </ul>
{% endblock navigation-bar %}
{% block page_body %}
    <div class="container mt-5">
        <h1 class="text-center mb-4">{{ profile.user.username }}'s Profile</h1>
        <div class="row">
            <!-- Profile Info Column -->
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        <h4>Profile Picture</h4>
                    </div>
                    <div class="card-body text-center">
                        {% if profile.profile_picture %}
                            <img src="{{ profile.profile_picture.url }}"
                                 alt="Profile Picture"
                                 class="img-fluid rounded-circle"
                                 style="width: 200px;
                                        height: 200px">
                        {% else %}
                            <img src="https://via.placeholder.com/200"
                                 alt="Default Profile Picture"
                                 class="img-fluid rounded-circle">
                        {% endif %}
                    </div>
                </div>
            </div>
            <!-- Profile Details Column -->
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h4>Profile Details</h4>
                    </div>
                    <div class="card-body">
                        <div class="mb-3">
                            <strong>First Name:</strong>
                            <p>{{ profile.user.first_name }}</p>
                        </div>
                        <div class="mb-3">
                            <strong>Last Name:</strong>
                            <p>{{ profile.user.last_name }}</p>
                        </div>
                        <div class="mb-3">
                            <strong>Email:</strong>
                            <p>{{ profile.user.email }}</p>
                        </div>
                        <div class="mb-3">
                            <strong>Bio:</strong>
                            <p>{{ profile.bio|default:"No bio available" }}</p>
                        </div>
                        <div class="text-center">
                            <a href="{% url 'profile_edit' %}" class="btn btn-primary">Edit Profile</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock page_body %}

blog_post_management_system/accounts/templates/accounts/registration.html
{% extends "base_layout.html" %}
{% load static %}
{% block title %}
    Registration Page
{% endblock title %}
{% block navigation-bar %}
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'user-login' %}">Login</a>
        </li>
    </ul>
{% endblock navigation-bar %}
{% block page_body %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4">
                <div class="card shadow-sm">
                    <div class="card-header text-center">
                        <h4>Registration</h4>
                    </div>
                    <!-- Display non-field errors -->
                    {% if form.non_field_errors %}
                        <div class="text-danger">
                            <ul>
                                {% for error in form.non_field_errors %}<li>{{ error }}</li>{% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- Username Field -->
                            <div class="mb-3">
                                <label for="id_username" class="form-label">Username</label>
                                <input type="text"
                                       name="username"
                                       id="id_username"
                                       class="form-control"
                                       value="{{ form.username.value|default:'' }}">
                                {% if form.username.errors %}
                                    <ul>
                                        {% for error in form.username.errors %}<li class="text-danger">{{ error }}</li>{% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                            <!-- First Name Field -->
                            <div class="mb-3">
                                <label for="id_first_name" class="form-label">First Name</label>
                                <input type="text"
                                       name="first_name"
                                       id="id_first_name"
                                       class="form-control"
                                       value="{{ form.first_name.value|default:'' }}">
                                {% if form.first_name.errors %}
                                    <ul>
                                        {% for error in form.first_name.errors %}<li class="text-danger">{{ error }}</li>{% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                            <!-- Last Name Field -->
                            <div class="mb-3">
                                <label for="id_last_name" class="form-label">Last Name</label>
                                <input type="text"
                                       name="last_name"
                                       id="id_last_name"
                                       class="form-control"
                                       value="{{ form.last_name.value|default:'' }}">
                                {% if form.last_name.errors %}
                                    <ul>
                                        {% for error in form.last_name.errors %}<li class="text-danger">{{ error }}</li>{% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                            <!-- Email Field -->
                            <div class="mb-3">
                                <label for="id_email" class="form-label">Email</label>
                                <input type="email"
                                       name="email"
                                       id="id_email"
                                       class="form-control"
                                       value="{{ form.email.value|default:'' }}">
                                {% if form.email.errors %}
                                    <ul>
                                        {% for error in form.email.errors %}<li class="text-danger">{{ error }}</li>{% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                            <!-- Password Field -->
                            <div class="mb-3">
                                <label for="id_password1" class="form-label">Password</label>
                                <input type="password"
                                       name="password1"
                                       id="id_password1"
                                       class="form-control"
                                       value="{{ form.password1.value|default:'' }}">
                                {% if form.password1.errors %}
                                    <ul>
                                        {% for error in form.password1.errors %}<li class="text-danger">{{ error }}</li>{% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                            <!-- Confirm Password Field -->
                            <div class="mb-3">
                                <label for="id_password2" class="form-label">Confirm Password</label>
                                <input type="password"
                                       name="password2"
                                       id="id_password2"
                                       class="form-control"
                                       value="{{ form.password2.value|default:'' }}">
                                {% if form.password2.errors %}
                                    <ul>
                                        {% for error in form.password2.errors %}<li class="text-danger">{{ error }}</li>{% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary w-100">Register</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock page_body %}